// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8wI6ZzO-e-eouLpU1J7j3BbRX7AhVOA',
    appId: '1:989817367971:web:ed59cca06d4b3bdd7a3e16',
    messagingSenderId: '989817367971',
    projectId: 'gestioncarte-8c596',
    authDomain: 'gestioncarte-8c596.firebaseapp.com',
    storageBucket: 'gestioncarte-8c596.firebasestorage.app',
    measurementId: 'G-GZ7RJZ07ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYsqr48k6XG1K3DjRdDv5TP1U_yvvEwOU',
    appId: '1:989817367971:android:1fcfb3fe4137bfcd7a3e16',
    messagingSenderId: '989817367971',
    projectId: 'gestioncarte-8c596',
    storageBucket: 'gestioncarte-8c596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1lc4puUtjMubnmn1qiYZ_CNyyoiJFnE',
    appId: '1:989817367971:ios:d88aa00ac748dc2d7a3e16',
    messagingSenderId: '989817367971',
    projectId: 'gestioncarte-8c596',
    storageBucket: 'gestioncarte-8c596.firebasestorage.app',
    iosClientId: '989817367971-1t299tq83ohpc83sgpq96sd9ka033dft.apps.googleusercontent.com',
    iosBundleId: 'com.cardmanager.cardManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe1lc4puUtjMubnmn1qiYZ_CNyyoiJFnE',
    appId: '1:989817367971:ios:d88aa00ac748dc2d7a3e16',
    messagingSenderId: '989817367971',
    projectId: 'gestioncarte-8c596',
    storageBucket: 'gestioncarte-8c596.firebasestorage.app',
    iosClientId: '989817367971-1t299tq83ohpc83sgpq96sd9ka033dft.apps.googleusercontent.com',
    iosBundleId: 'com.cardmanager.cardManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_8wI6ZzO-e-eouLpU1J7j3BbRX7AhVOA',
    appId: '1:989817367971:web:f8f6dd59102ee2a67a3e16',
    messagingSenderId: '989817367971',
    projectId: 'gestioncarte-8c596',
    authDomain: 'gestioncarte-8c596.firebaseapp.com',
    storageBucket: 'gestioncarte-8c596.firebasestorage.app',
    measurementId: 'G-X9K7VZ9CNB',
  );
}
